[build]
  command = "npm install --force && npm run build"
  publish = ".next" 

[context.production.environment]
  NPM_FLAGS = "--force"

  [[redirects]]
    from = "/*"
    to = "https://amsvn.net"
    status = 301
    force = true
